# Starship プロンプト設定


## VCS / プロジェクトメタデータ

[git_status]
disabled = true

[package]
disabled = true


## 言語ランタイム / ビルドツール

[gradle]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true


## インフラ / クラウド

[aws]
disabled = true

[gcloud]
disabled = true

[terraform]
disabled = true
